name: fedscale
channels:
  - miniconda
dependencies:
  - python=3.8
  - numpy
  - tensorboard
  - torchvision
  - transformers
  - tensorboardX==2.1
  - overrides==3.1.0
  - PyYAML
  - pytest
  - grpcio==1.40.0
  - gym
  - jupyter
  - pillow==9
  - sentencepiece
  - gdown
  - h5py
  - librosa==0.7.2
  - resampy==0.3.1
  - wandb
  - pip:
    - torch_optimizer
    - kubernetes
    - python-levenshtein==0.12.0
    - sox==1.3.7
    - SoundFile
#    - scipy==1.4.1
#    - matplotlib==3.1.3
#    - torch_baidu_ctc==0.3.0
#    - torch
#    - pandas==1.1.0
