name: Documentation
title: "[<FedScale component: Core|Dataloader|etc...>] "
description: Report an issue with the FedScale documentation
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: Thank you for helping us improve the FedScale documentation!

  - type: textarea
    attributes:
      label: Description
      description: |
        Tell us about the change you'd like to see. For example, "I'd like to
        see more examples of how to personalize `fedscale.aggregator`."
    validations:
      required: true