# Configuration file of Google SPEECH training experiment
exp_path: $MAIN_PATH/core

# Entry function of executor and aggregator under $exp_path
executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: ""
    ssh_private_key: ~/.ssh/id_rsa

# cmd to run before we can indeed run oort (in order)
setup_commands:
    - source $CONDA_PATH/etc/profile.d/conda.sh
    - conda activate $CONDA_ENV
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PATH/lib

# ========== Additional job configuration ========== 
# Default parameters are specified in argParser.py, wherein more description of the parameter can be found

job_conf: 
    - log_path: $MAIN_PATH/core/evals # Path of log files
    - job_name: google_speech                   # Generate logs under this folder: log_path/job_name/time_stamp
    - task: speech
    - total_worker: 30                      # Number of participants per round, we use K=10 in our paper, large K will be much slower
    - data_set: google_speech                     # Dataset: openImg, google_speech, stackoverflow
    - data_dir: $DATA_PATH                            # Path of the dataset
    - data_map_dir: $DATA_PATH/client_data_mapping             # Allocation of data to each client, turn to iid setting if not provided
    - device_conf_file: $MAIN_PATH/dataset/data/device_info/client_device_capacity     # Path of the client trace
    - device_avail_file: $MAIN_PATH/dataset/data/device_info/client_behave_trace
    - model: resnet34                            # Models: e.g., shufflenet_v2_x2_0, mobilenet_v2, resnet34, albert-base-v2
    - sample_mode: $SAMPLER
    - gradient_policy: "fed-avg"                 # {"fed-yogi", "fed-prox", "fed-avg"}, "fed-avg" by default
    - eval_interval: 50                     # How many rounds to run a testing on the testing set
    - epochs: 501                          # Number of rounds to run this training. We use 1000 in our paper, while it may converge w/ ~400 rounds
    - filter_less: 11                       # Remove clients w/ less than 21 samples
    #- filter_more: 21                       # Remove clients w/ more than 21 samples
    - used_samples: 0                       # Remove clients w/ more than 21 samples
    - num_loaders: 2
    - yogi_eta: 3e-3 
    - yogi_tau: 1e-8
    - local_steps: 5
    - learning_rate: 0.01
    - batch_size: 20
    - test_bsz: 10
    - use_wandb: 0
    - stale_update: $STALEUPDATES
    - deadline: $DEADLINE
    - target_ratio: $TARGETRATIO
    - last_worker: 0
    - random_behv: $RANDBEHV
    - avail_priority: $AVAILPRIO
    - avail_probability: $AVAILPROP
    - partitioning: 4
    - dirichlet_alpha: 0.1
    - zipf_param: 1.95
    - filter_class_ratio: 0.4
    - total_clients: $CLIENTS
    - exp_type: $EXPTYPE
    - overcommitment: $OVERCOMMIT
    - stale_factor: $STALE_FACTOR
    - send_delta: 0
    - model_boost: 0
    - stale_all: 0
    - adapt_selection: 1
    - sample_seed: $SAMPLESEED
    - wandb_key: $WANDB_API_KEY
    - wandb_entity: $WANDB_ENTITY
    - wandb_tags: $TAGS
    - use_cuda: True
    - zipf_param: 1.95
    - val_ratio: 0.1
    - bandwidth_profiles_dir: $MAIN_PATH/dataset/data/device_info/client_device_traces.csv #Farz - path of client trace for dynamic networks
    - scale_sys: $SCALE_SYS
    - scale_sys_percent: $SCALE_SYS_PERCENT
    - dropout_ratio: $DROPOUT_RATIO
    - scale_coff: $SCALE_COFF
    - stale_beta: $STALE_BETA

